name: Daily Heatmap Update

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  generate_and_push_heatmap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master  # your default branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run heatmap script
        run: python notion_heatmap/notion_heatmap.py

      - name: Configure git
        run: |
          git config --global user.name "riyajivani"
          git config --global user.email "riyajivani8@gmail.com"

      - name: Commit and push heatmap image
        run: |
          git checkout -b gh-pages || git checkout gh-pages
          mkdir -p images
          mv heatmap.png images/heatmap.png
          git add images/heatmap.png
          git commit -m "Daily heatmap update $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Notion with new image URL
        run: |
          python notion_heatmap/update_notion_image.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          IMAGE_URL: https://raw.githubusercontent.com/riyajivani/notion-heatmap-images/gh-pages/images/heatmap.png