name: Daily Heatmap Update

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  generate_and_push_heatmap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master  # your default branch
          fetch-depth: 0         # full history for pushing
          persist-credentials: true  # important to push with default token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run heatmap script
        run: python notion_heatmap/notion_heatmap.py

      - name: Prepare gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout -b gh-pages

      - name: Move heatmap to images folder
        run: |
          mkdir -p images
          mv heatmap.png images/heatmap.png
      
      - name: Configure git
        run: |
          git config --global user.name "riyajivani"
          git config --global user.email "riyajivani8@gmail.com"

      - name: Commit and push heatmap image   # <-- indentation fixed here
        env:
          GIT_ASKPASS: /bin/echo
          GIT_USERNAME: riyajivani
          GIT_PASSWORD: ${{ secrets.PAT_TOKEN }}
        run: |
          git add images/heatmap.png
          git diff --cached --quiet || git commit -m "Daily heatmap update $(date +'%Y-%m-%d')"
          git push https://$GIT_USERNAME:$GIT_PASSWORD@github.com/riyajivani/notion-heatmap-task-images.git gh-pages --force

      - name: Update Notion with new image URL
        run: |
          python notion_heatmap/update_notion_image.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          IMAGE_URL: https://raw.githubusercontent.com/riyajivani/notion-heatmap-images/gh-pages/images/heatmap.png
